[package]
name = "shade" # Will keep it like this for now
version = "0.1.0" # Not sure if I should change it
edition = "2021" 

[dependencies]
macroquad = "0.4.0" # Adding the macroquad library itself
